name: Basic CI

on:
  workflow_dispatch:
  pull_request:
    branches: [main, master] # Runs PRs targeting these branches

jobs:
  quality:
    runs-on: ubuntu-latest # The Host Machine (hardware)
    timeout-minutes: 5

    steps:
      # Download code into the container
      - name: Check out repository
        uses: actions/checkout@v4

      # Install pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      # Setup Node with pnpm caching
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      # Clean install for pnpm; if lockfile needs to be updated, fail the build
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Linting
        run: make lint

      - name: Run Typecheck
        run: make typecheck

  unit-tests:
    runs-on: ubuntu-latest
    needs: quality
    timeout-minutes: 5
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Integration tests
        run: make test-be-unit

  e2e-tests:
    runs-on: ubuntu-latest
    environment: defaultenv
    needs: quality
    timeout-minutes: 10
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run e2e tests
        run: make test-be-e2e
